### ISSUE TITLE
tls support

### ISSUE THREAD

**Issue by izarraga** [debug-ito/AnyEvent-WebSocket-Server#2]
Hello,

I use this perl module and works well, but i need TLS support.

Will you implement it ?

Regards,

Igor

**Comment by debug-ito** [comment]
If you need it, I'll try, but first I have to think about how I can implement it. Do you have any good idea?

As an alternative, I think you can use nginx or something to terminate TLS streams and reverse-proxy them as plain WebSocket streams.

**Comment by izarraga** [comment]
Hello,

Perphaps it can be done with AnyEvent::TLS, i use it to make SSL server
sockets.

Regards,

Igor

2016-07-22 15:48 GMT+02:00 Toshio Ito notifications@github.com:

**Comment by debug-ito** [comment]
Thanks!

I'm now working on this issue in `tls` branch. I already wrote API document, but didn't implement anything yet. If you have problem about the added API, just tell me.

**Comment by debug-ito** [comment]
version 0.071 is officially released.
